# Generated by Django 5.0.2 on 2024-02-28 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='fecha_publi',
            field=models.DateField(null=True, verbose_name='01/01/1999'),
        ),
    ]
