# Generated by Django 5.0.2 on 2024-02-28 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_fecha_publi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='fecha_publi',
            field=models.DateField(null=True, verbose_name='DD/MM/AA'),
        ),
    ]
